### ISSUE TITLE
Cannot access a disposed object

### ISSUE THREAD

**Issue by ulkaio** [Guarrdon/Serilog.Sinks.RedisStream#3]
Getting this exception while try to Log.Information from a separate file other than the one where Serilog and RedisStream is configured. Here is the configuration code

```
var config = new RedisStreamSinkConfiguration
{
    RedisConnectionString = "localhost:6379",
    RedisStreamName = "SomeApp"
};

Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Is(logEventLevel)
    .WriteTo.Console()
    .WriteTo.RedisStreamSink(config)
    .CreateLogger();
```

```
Unhandled Exception: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'DESKTOP'.
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteAsyncImpl[T](Message message, ResultProcessor`1 processor, Object state, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 2122
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MADESKTOP'.
   at StackExchange.Redis.RedisBase.ExecuteAsync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisBase.cs:line 47
   at StackExchange.Redis.RedisDatabase.StreamAddAsync(RedisKey key, RedisValue streamField, RedisValue streamValue, Nullable`1 messageId, Nullable`1 maxLength, Boolean useApproximateMaxLength, CommandFlags flags) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisDatabase.cs:line 1755
   at SeriLog.Sinks.RedisStream.RedisStreamSink.Emit(LogEvent logEvent)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()   at StackExchange.Redis.ConnectionMultiplexer.ExecuteAsyncImpl[T](Message message, ResultProcessor`1 processor, Object state, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 2122
   at StackExchange.Redis.RedisBase.ExecuteAsync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisBase.cs:line 47
   at StackExchange.Redis.RedisDatabase.StreamAddAsync(RedisKey key, RedisValue streamField, RedisValue streamValue, Nullable`1 messageId, Nullable`1 maxLength, Boolean useApproximateMaxLength, CommandFlags flags) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisDatabase.cs:line 1755
   at SeriLog.Sinks.RedisStream.RedisStreamSink.Emit(LogEvent logEvent)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()```

Any idea what's might wrong here?

**Comment by Guarrdon** [comment]
Thanks for raising this issue.  It has an impact across both my log4Net appender and the Redis sink variations of the RedisStream implementation.

I thought I had solved this following the pattern recommended in 
[StackExchance.Redis Basics](https://stackexchange.github.io/StackExchange.Redis/Basics).

I don't experience the issue in my tests where I pushed the Logger to a separate class and executed multiple logs.
However,  I do see a potential problem in that I am leveraging a **using** statement around the connection which is likely defeating the purpose of reusing the connection.

Evaluating new code changes with no **using** statement now.

**Comment by ulkaio** [comment]
Thanks for sharing your findings.

**Comment by kisalay1988** [comment]
Is there any update on this issue? I am trying to use your package and stuck with this same issue :)

**Comment by Guarrdon** [comment]
Sorry for the delay on the response.  Thanks for the issue notes.

I honestly cannot reproduce this issue on my development machines.  However, I did some more research and decided to change how I was holding open the IConnectionMultiplexer instance.
Pre-Release made (v1.1) supporting the fix.
Not yet released to Nuget, but you can try out the change from src.

Will leave issue open until I officially release to Nuget in a few days.

**Comment by md-redwan-hossain** [comment]
facing the same issue.
